- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: 
    - reload nginx

- name: Create nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  notify: 
    - reload nginx
